version: 1.2

workflows:
  - name: ONT_PolishDraftAndQC
    subclass: WDL
    primaryDescriptorPath: wdls/workflows/ONT_PolishDraftAndQC.wdl
    latestTagAsDefault: 'true'
    authors:
      - orcid: "0000-0002-6006-0641"
      - name: "Michael J. Foster"
      - email: "mfoster11@mgh.harvard.edu"
